---
title: "WESAD Model Fitting and Validation"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkgtest, echo=FALSE}
# source: https://stackoverflow.com/questions/9341635/check-for-installed-packages-before-running-install-packages
pkgTest <- function(x)
  {
    if (!require(x,character.only = TRUE))
    {
      install.packages(x,repos = "http://cran.r-project.org",dep=TRUE)
        if(!require(x,character.only = TRUE)) stop("Package not found")
    }
  }
```

```{r check package,include=FALSE}
pkgTest("ggplot2")
pkgTest("readr")
pkgTest("caret")
pkgTest("broom")
pkgTest("tidyverse")
pkgTest("dplyr")
pkgTest("knitr")
pkgTest("tibble")
pkgTest("pROC") #ROC curves
pkgTest("arm") #binned residuals
pkgTest("questionr") #odds ratio function
#pkgTest("car")
#pkgTest("InformationValue")
```

## Model Fitting and Validation 
```{r choosing inputs}
data_for_model = read.csv("WESAD-one-sec-shift.csv")
good_columns = c('affect', 'subject_id', 'chest_EDA_slope', 
                'wrist_EDA_slope', 'chest_RESP_breath_rate',
                'chest_RESP_volume', 'chest_SCR_num_segments', 'wrist_SCR_num_segments',
               'chest_ACC_magnitude_mean', 'wrist_ACC_magnitude_mean', 'chest_TEMP_mean', 'wrist_TEMP_mean', 'chest_ECG_HRV_mean', 'wrist_BVP_HRV_mean')
data_for_model = data_for_model[names(data_for_model) %in% good_columns]
data_for_model$affect2 <- ifelse(data_for_model$affect == 'stress', 1, 0)
data_for_model
```

```{r correlations}
## checking for correlation between the inputs of our model
num_data2 = data_for_model
word_cols2 = c('affect', 'subject_id')
num_data2<-num_data2[,!names(num_data2) %in% word_cols2]
num_data2

cor_all2<- round(cor(num_data2, method = "pearson"),2)
cor_all2

cor_df2 <- as.data.frame(as.table(cor_all2))%>%
  arrange(desc(Freq)) %>% filter(abs(Freq) > 0.7)

cor_df2
```

```{r create training and test data}
set.seed(012)
## Modeling
percent_train = 0.8
train = data.frame()
test = data.frame()
for (id in unique(data_for_model$subject_id)) {
  subject_df =  data_for_model[data_for_model$subject_id == id,]
  train_indices = sample(nrow(subject_df), floor(percent_train * nrow(subject_df)))
  train = rbind(train, subject_df[train_indices,])
  test = rbind(test, subject_df[-train_indices,])
}
```

### Full model without Subject ID
```{r full model}
full_logistic_model = glm(affect2 ~ . - subject_id -affect, data=train, maxit=100)
summary(full_logistic_model)
probabilities = predict(full_logistic_model, test, type='response')
predictions = ifelse(probabilities > 0.5, 'stress', 'amusement')
mean(predictions == test$affect) # accuracy
1- mean(predictions == test$affect) #misclassification error
```

```{r full model validation}
#confusion matrix
test_affect = as.factor(test$affect) #truth
predictions_frac = as.factor(predictions) #predicted
confusionMatrix(predictions_frac, test_affect)


#binned residual plot
binnedplot(probabilities,residuals(full_logistic_model, type = "response"), nclass = NULL, 
           xlab = "Expected Values", ylab = "Average residual", main = "Binned residual plot for full model without subject id", cex.pts = 0.8, col.pts = 1, col.int = "gray")

#ROC CURVE
test_roc = roc(test$affect2 ~ probabilities, plot = TRUE, print.auc = TRUE)
```

### Full model with Subject ID
```{r full model with subject id}
full_model_with_subject_id = glm(affect2 ~ . -affect, data=train, maxit=100)
summary(full_model_with_subject_id)
full_probabilities_id = predict(full_model_with_subject_id, test, type='response')
full_predictions_id = ifelse(full_probabilities_id > 0.5, 'stress', 'amusement')
mean(full_predictions_id == test$affect) # accuracy
1- mean(full_predictions_id == test$affect) #misclassification error
```

```{r full model with subject id validation}
#confusion matrix
test_affect = as.factor(test$affect) #truth
full_predictions_id_frac = as.factor(full_predictions_id) #predicted
confusionMatrix(full_predictions_id_frac, test_affect)

#binned residual plot
binnedplot(full_probabilities_id,residuals(full_model_with_subject_id, type = "response"), nclass = NULL, 
           xlab = "Expected Values", ylab = "Average residual", main = "Binned residual plot for full model with subject id", cex.pts = 0.8, col.pts = 1, col.int = "gray")

#ROC CURVE
test_roc = roc(test$affect2,full_probabilities_id , plot = TRUE, print.auc = TRUE)
```

### Wrist model without Subject ID
```{r full wrist model}
wrist_logistic_model = glm(affect2 ~ wrist_ACC_magnitude_mean+wrist_BVP_HRV_mean+wrist_EDA_slope+wrist_SCR_num_segments+wrist_TEMP_mean - subject_id -affect, data=train, maxit=100)
summary(wrist_logistic_model)
wrist_probabilities = predict(wrist_logistic_model, test, type='response')
wrist_predictions = ifelse(wrist_probabilities > 0.5, 'stress', 'amusement')
mean(wrist_predictions == test$affect) # accuracy
1- mean(wrist_predictions == test$affect) #misclassification error
```

```{r full wrist model validation}
#confusion matrix
test_affect = as.factor(test$affect)
wrist_predictions_fac = as.factor(wrist_predictions)
confusionMatrix(wrist_predictions_fac, test_affect)

#binned residual plot
binnedplot(wrist_probabilities,residuals(wrist_logistic_model, type = "response"), nclass = NULL, 
           xlab = "Expected Values", ylab = "Average residual", main = "Binned residual plot for wrist model without subject id", cex.pts = 0.8, col.pts = 1, col.int = "gray")

#ROC CURVE
test_roc = roc(test$affect2 ~ wrist_probabilities, plot = TRUE, print.auc = TRUE)
```

### Wrist model with Subject ID
```{r full wrist model with subject id}
wrist_logistic_model_id = glm(affect2 ~ wrist_ACC_magnitude_mean+wrist_BVP_HRV_mean+wrist_EDA_slope+wrist_SCR_num_segments+wrist_TEMP_mean + subject_id -affect, data=train, maxit=100)
summary(wrist_logistic_model_id)
wrist_probabilities_id = predict(wrist_logistic_model_id, test, type='response')
wrist_predictions2_id = ifelse(wrist_probabilities_id > 0.5, 'stress', 'amusement')
mean(wrist_predictions2_id == test$affect) # accuracy
1- mean(wrist_predictions2_id == test$affect) #misclassification error
```

```{r full wrist model with subject id validation}
#confusion matrix
test_affect = as.factor(test$affect)
wrist_predictions2_id_fac = as.factor(wrist_predictions2_id)
confusionMatrix(wrist_predictions2_id_fac, test_affect)

#binned residual plot
binnedplot(wrist_probabilities_id,residuals(wrist_logistic_model_id, type = "response"), nclass = NULL, 
           xlab = "Expected Values", ylab = "Average residual", main = "Binned residual plot for wrist model with subject id", cex.pts = 0.8, col.pts = 1, col.int = "gray")

#ROC CURVE
test_roc = roc(test$affect2 ~ wrist_probabilities_id, plot = TRUE, print.auc = TRUE)
```

